<a href="https://colab.research.google.com/github/felipesayegg/Python-para-Data-Science/blob/main/Numpy_curso.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np # chamando a biblioteca

O parâmetro usecols=np.arange(1, 88, 1) é utilizado para indicar quais colunas do arquivo você deseja carregar. Vamos entender melhor como isso funciona:

np.arange(1, 88, 1): Essa função do NumPy gera um array com uma sequência de números. No seu caso, ela cria uma lista que começa em 1, vai até 87 e incrementa de 1 em 1. O resultado será um array que contém os números de 1 a 87.

Uso em loadtxt(): Ao passar esse array para o parâmetro usecols, você está dizendo ao NumPy para carregar apenas as colunas correspondentes a esses índices. Como a contagem de colunas começa em 0, isso significa que você está carregando todas as colunas do arquivo, exceto a primeira (que contém os nomes das cidades).

In [3]:
url = 'https://raw.githubusercontent.com/alura-cursos/numpy/dados/apples_ts.csv'

In [4]:
dado = np.loadtxt(url, delimiter= ',', usecols = np.arange(1,88,1)) # carregou os dados usando o np que é otimo para carregar dados numericos diferente de pandas.
# o delimiter é para avisar a divisão dos sados do arquivo csv e o usecils = .np.arange est informando a coluna de inicio ate a final que vamos trabalhar e de quantas vamos pular
# Usei usando url para puxar os dados

In [5]:
dado

array([[  1.2013,   2.2013,   3.2013,   4.2013,   5.2013,   6.2013,
          7.2013,   8.2013,   9.2013,  10.2013,  11.2013,  12.2013,
          1.2014,   2.2014,   3.2014,   4.2014,   5.2014,   6.2014,
          7.2014,   8.2014,   9.2014,  10.2014,  11.2014,  12.2014,
          1.2015,   2.2015,   3.2015,   4.2015,   5.2015,   6.2015,
          7.2015,   8.2015,   9.2015,  10.2015,  11.2015,  12.2015,
          1.2016,   2.2016,   3.2016,   4.2016,   5.2016,   6.2016,
          7.2016,   8.2016,   9.2016,  10.2016,  11.2016,  12.2016,
          1.2017,   2.2017,   3.2017,   4.2017,   5.2017,   6.2017,
          7.2017,   8.2017,   9.2017,  10.2017,  11.2017,  12.2017,
          1.2018,   2.2018,   3.2018,   4.2018,   5.2018,   6.2018,
          7.2018,   8.2018,   9.2018,  10.2018,  11.2018,  12.2018,
          1.2019,   2.2019,   3.2019,   4.2019,   5.2019,   6.2019,
          7.2019,   8.2019,   9.2019,  10.2019,  11.2019,  12.2019,
          1.202 ,   2.202 ,   3.202 ],
       [ 

Em Ciência de Dados existem várias situações nas quais precisamos avaliar dados relacionados a eventos periódicos que acontecem com uma data fixa ou pré-determinada, pois estes podem possuir alguma influência no fenômeno que queremos analisar. Um exemplo de evento que movimenta muitos(as) brasileiros(as) e várias outras pessoas em diferentes países é a Copa do Mundo, organizada pela Federação Internacional de Futebol (FIFA).

Dado o exemplo de evento periódico acima, crie um array, utilizando a função np.arange(), que liste todos os anos nos quais aconteceram ou estão previstos de acontecer a Copa do Mundo, considerando o intervalo fechado dos anos de 2000 a 2102.

In [6]:
import numpy as np #  Biblioteca numpy

ano_inicial = 2002
ano_final = 2102
np.arange(ano_inicial, ano_final + 1, 4) # função arange leva onde comeca o array, o final + 1 para chegar no valor + quanto vai ser o pulo para criar o array.

array([2002, 2006, 2010, 2014, 2018, 2022, 2026, 2030, 2034, 2038, 2042,
       2046, 2050, 2054, 2058, 2062, 2066, 2070, 2074, 2078, 2082, 2086,
       2090, 2094, 2098, 2102])

In [7]:
import numpy as np
import time

# cria uma lista com 1000000 elementos
lista = list(range(1000000))

# transforma a lista em um array Numpy
array = np.array(lista)

# começa a cronometrar o tempo para a operação com a lista
start_time = time.time()

# realiza a operação de elevar ao quadrado cada elemento da lista
lista_quadrado = [i**2 for i in lista]

# para o cronômetro
list_time = time.time() - start_time

# começa a cronometrar o tempo para a operação com o array
start_time = time.time()

# realiza a operação de elevar ao quadrado cada elemento do array
array_quadrado = array**2

# para o cronômetro
array_time = time.time() - start_time

print("Tempo da operação com a lista: ", list_time)
print("Tempo da operação com o array: ", array_time)

Tempo da operação com a lista:  0.09079480171203613
Tempo da operação com o array:  0.0042116641998291016


In [8]:
dado.ndim # vai dizer se o database é linha e coluna quando der 2

2

In [9]:
dado.size # quantos elementos tem

522

In [10]:
dado.shape # mostrando quantas linhas tem e colunas

(6, 87)

In [13]:
dado_transposto = dado.T # imagina que a minha array principal inverteu a linha e coluna

In [22]:
dado_transposto # imprimindo os dados transpostos

array([[  1.2013,  79.72  ,  42.67  ,  62.55  ,  48.26  ,  71.25  ],
       [  2.2013,  81.08  ,  44.37  ,  62.73  ,  51.01  ,  71.35  ],
       [  3.2013,  79.68  ,  44.73  ,  63.43  ,  50.91  ,  70.9   ],
       [  4.2013,  79.8   ,  46.75  ,  63.83  ,  53.94  ,  71.92  ],
       [  5.2013,  80.63  ,      nan,  66.06  ,  61.27  ,  72.91  ],
       [  6.2013,  80.8   ,  51.59  ,  69.22  ,  65.44  ,  74.39  ],
       [  7.2013,  80.28  ,  57.8   ,  72.07  ,  56.51  ,  73.1   ],
       [  8.2013,  78.99  ,  62.14  ,  69.31  ,  53.    ,  70.24  ],
       [  9.2013,  76.77  ,  56.76  ,  65.18  ,  43.87  ,  69.12  ],
       [ 10.2013,  76.09  ,  50.85  ,  62.13  ,  42.12  ,  68.98  ],
       [ 11.2013,  76.36  ,  46.43  ,  64.17  ,  43.98  ,  68.58  ],
       [ 12.2013,  77.16  ,  46.73  ,  65.5   ,  44.66  ,  69.5   ],
       [  1.2014,  77.5   ,  45.85  ,  66.85  ,  47.73  ,  70.14  ],
       [  2.2014,  79.03  ,  49.25  ,  68.38  ,  52.31  ,  70.58  ],
       [  3.2014,  80.28  ,  48.14

In [26]:
datas = dado_transposto[:,0]
datas

array([ 1.2013,  2.2013,  3.2013,  4.2013,  5.2013,  6.2013,  7.2013,
        8.2013,  9.2013, 10.2013, 11.2013, 12.2013,  1.2014,  2.2014,
        3.2014,  4.2014,  5.2014,  6.2014,  7.2014,  8.2014,  9.2014,
       10.2014, 11.2014, 12.2014,  1.2015,  2.2015,  3.2015,  4.2015,
        5.2015,  6.2015,  7.2015,  8.2015,  9.2015, 10.2015, 11.2015,
       12.2015,  1.2016,  2.2016,  3.2016,  4.2016,  5.2016,  6.2016,
        7.2016,  8.2016,  9.2016, 10.2016, 11.2016, 12.2016,  1.2017,
        2.2017,  3.2017,  4.2017,  5.2017,  6.2017,  7.2017,  8.2017,
        9.2017, 10.2017, 11.2017, 12.2017,  1.2018,  2.2018,  3.2018,
        4.2018,  5.2018,  6.2018,  7.2018,  8.2018,  9.2018, 10.2018,
       11.2018, 12.2018,  1.2019,  2.2019,  3.2019,  4.2019,  5.2019,
        6.2019,  7.2019,  8.2019,  9.2019, 10.2019, 11.2019, 12.2019,
        1.202 ,  2.202 ,  3.202 ])

In [27]:
preços = dado_transposto[:,1:6]
preços

array([[ 79.72,  42.67,  62.55,  48.26,  71.25],
       [ 81.08,  44.37,  62.73,  51.01,  71.35],
       [ 79.68,  44.73,  63.43,  50.91,  70.9 ],
       [ 79.8 ,  46.75,  63.83,  53.94,  71.92],
       [ 80.63,    nan,  66.06,  61.27,  72.91],
       [ 80.8 ,  51.59,  69.22,  65.44,  74.39],
       [ 80.28,  57.8 ,  72.07,  56.51,  73.1 ],
       [ 78.99,  62.14,  69.31,  53.  ,  70.24],
       [ 76.77,  56.76,  65.18,  43.87,  69.12],
       [ 76.09,  50.85,  62.13,  42.12,  68.98],
       [ 76.36,  46.43,  64.17,  43.98,  68.58],
       [ 77.16,  46.73,  65.5 ,  44.66,  69.5 ],
       [ 77.5 ,  45.85,  66.85,  47.73,  70.14],
       [ 79.03,  49.25,  68.38,  52.31,  70.58],
       [ 80.28,  48.14,  68.77,  56.8 ,  70.78],
       [ 80.05,  49.18,  69.32,  51.15,  72.78],
       [ 78.11,  49.49,  69.77,  54.63,  72.84],
       [ 76.9 ,  49.83,  70.17,  55.8 ,  74.74],
       [ 77.68,  49.14,  70.76,  57.31,  76.43],
       [ 76.05,  63.21,  75.16,  53.81,  81.2 ],
       [ 75.53,  61.

Chegou a hora de você testar os conhecimentos desenvolvidos durante a aula. Para isso, vamos utilizar outro dataset em um desafio que será desenvolvido no decorrer do curso. Esse dataset é uma versão modificada do arquivo Oranges vs. Grapefruit presente no site do Kaggle. Portanto, utilizaremos o arquivo raw disponível no GitHub.

Nessa etapa, você deve efetuar a leitura dos dados. Para isso, importe a NumPy e use a função loadtxt. Use o link da url e o parâmetro usecols para pular a primeira coluna. É possível usar np.arange para criar a sequência de números que representam as colunas. Por fim, também é necessário incluir o parâmetro skiprows=1 para que a primeira linha de texto seja desconsiderada na leitura do arquivo.



In [15]:
import numpy as np

In [17]:
url = 'https://raw.githubusercontent.com/allanspadini/numpy/dados/citrus.csv'

In [29]:
orange_dados = np.loadtxt(url, delimiter= ',', usecols=np.arange(1,6,1),skiprows=1) # skiprows=1 foi usado para não contar com a primeira linha do dataset por se tratar de string

In [30]:
orange_dados

array([[  2.96,  86.76, 172.  ,  85.  ,   2.  ],
       [  3.91,  88.05, 166.  ,  78.  ,   3.  ],
       [  4.42,  95.17, 156.  ,  81.  ,   2.  ],
       ...,
       [ 15.59, 256.5 , 168.  ,  82.  ,  20.  ],
       [ 15.92, 260.14, 142.  ,  72.  ,  11.  ],
       [ 16.45, 261.51, 152.  ,  74.  ,   2.  ]])

In [32]:
orange_dados.T

array([[  2.96,   3.91,   4.42, ...,  15.59,  15.92,  16.45],
       [ 86.76,  88.05,  95.17, ..., 256.5 , 260.14, 261.51],
       [172.  , 166.  , 156.  , ..., 168.  , 142.  , 152.  ],
       [ 85.  ,  78.  ,  81.  , ...,  82.  ,  72.  ,  74.  ],
       [  2.  ,   3.  ,   2.  , ...,  20.  ,  11.  ,   2.  ]])